### ISSUE TITLE
Unreal Engine / C++ Support

### ISSUE THREAD

**Issue by SaxonRah** [TheBerkin/rant#109]
I read allot of the code in Rant, yet couldn't find any information how one might use Rant alongside a game engine outside of Unity. I was thinking about using Unreal Engine or any C++ based engine. So I'd imagine i'd reference the Rant.dll that is compiled and i'd  setup an engine plugin that contains the dll, then i could possibly get access through COM? I guess what im asking is Rant managed?

**Comment by TheBerkin** [comment]
This implementation of Rant is written in C#, which is a CLI language, and therefore requires an implementation of the Common Language Runtime in order to be used.

One possible way to use Rant in Unreal would be to create a Mono runtime in your C++ code and run Rant through that, but I understand that's probably not the solution you want. Currently there are no C++ ports of Rant that I know of, and as a result, Rant does not currently have any support for native applications, including games built on UE4. Sorry about that.

**Comment by cpancake** [comment]
If you want to use Rant in Unreal Engine, and are OK with your game requiring the .NET framework to be able to run, you could build Rant with [Unmanaged Exports](https://www.nuget.org/packages/UnmanagedExports). This adds a layer of glue to the DLL that lets unmanaged programs use it. We removed it from Rant because we'd like to get a real native version of Rant going instead of using this not-really solution (also, it made build targets a lot more difficult to manage). It's an option if you want to give it a shot, though.
