### ISSUE TITLE
Replacers cause stack overflows if match count exceeds max stack size.

### ISSUE THREAD

**Issue by TheBerkin** [TheBerkin/Rant#39]
This can be observed using the following code:
```rant
[//x//:[char:x;64];y]
```
... whereas the following will work:
```rant
[//x//:[char:x;63];y]
```
This is because the default stack cap is set to 64 states. Currently, matches are queued in individual states (bad design decision on my part). This should be changed so that only one state is active for each active replacer at any given time. Consider pulling from a `MatchCollection`.

**Comment by cpancake** [comment]
So I've done a bunch of investigating into this issue, and while it's easy to pull from a MatchCollection instead of having a match per state, you still need to re-run the replacer pattern every match. Since there is a state per match currently, that means that everything runs smoothly. But having a single state for every match means repeating the same state multiple times. Due to the many stateful, interlocking components of the VM, this means that issues are run into with things like the state's reader being in a different position at the end of its run (easy to reset, though), or the output of each state growing every time it is run.

The last one is the main issue. While fixing all the state issues is just annoying, fixing the issue with the state output runs into an issue - mainly, that each state's output is added to the result stack by reference, meaning that clearing it on every run-through would clear the output already added to the result stack. To fix this, that'd require cloning every object placed on the result stack, heavily increasing memory and CPU usage. It might just be a better idea to remove the limit on the stack. I'll have to test them both out and see how they each compare.

**Comment by TheBerkin** [comment]
You might be able to mitigate the stack issue by placing a pre-blueprint on the state from which the replacer is called, which continuously pushes the next match evaulator state to the stack until all the matches are used up. If a pre-blueprint returns `true`, the VM will skip to the topmost state, so the pre-blueprint can be reused until the `MatchCollection` is completely traversed, at which point the `MatchCollection` can be popped and the pre-blueprint can return `false` to return to caller.

**Comment by cpancake** [comment]
I just thought of that in the shower and I don't know why I didn't think of that before.
