### ISSUE TITLE
Rant for Lua

### ISSUE THREAD

**Issue by 0tt** [TheBerkin/Rant#53]
It'd be really convenient to be able to use Rant in conjunction with Love2D. Something to consider.

**Comment by TheBerkin** [comment]
I'd have to do one of three things:
* Invoke .NET/Mono through a C++ library to run Rant
* Port Rant to C++ and call the library from Lua
* Port Rant to Lua

Given that I'm currently rewriting half the codebase, it would definitely be a while before I could look into this because features are always changing. Whichever above avenue I take, it would be a massive undertaking and would require a huge time investment. Perhaps if more people are interested, we could have a bunch of people working on this instead of just one.

Personally, I don't know a lot of Lua, so I'd probably spend more time learning Lua than being of any help with a port. I'd really like to see this happen, though... I can see potential applications in Garry's Mod as well as Love2D.

**Comment by cpancake** [comment]
When we get bytecode working, all ("all") you'd need to do would be to implement the VM. I mean, that's not exactly easy, but it's not as hard as implementing the whole thing.

**Comment by TheBerkin** [comment]
If the ASTs can be serialized, you can still write a VM for them.
