### ISSUE TITLE
Distinguish between word connotations

### ISSUE THREAD

**Issue by DaaOtt** [TheBerkin/Rant#56]
"Smelly" shouldn't be in the same pool as "fragrant". Perhaps a number from -5 to 5 on how positive or negative a words' connotation is?

**Comment by TheBerkin** [comment]
Good idea, and I agree; however, that is some very specific metadata, so I'm hesitant to make it a part of the DIC format itself. A numeric scale for connotation works as far as the sign of the number goes (I can tell if it's a good/bad connotation by checking if it's positive or not), but different people may perceive marginal changes in connotation differently under such a system. This particular feature would probably work better as a set of classes that establish a verbal rating system, rather than an arbitrary continuum.

If you would like, I can add you as a contributor to Rantionary.

**Comment by TheBerkin** [comment]
I started a wiki for dictionary guidelines and added a page on connotations. Let me know what you think: **[Link](https://github.com/RantLang/DictionaryGuidelines/wiki/Connotations)**

**Comment by DaaOtt** [comment]
Use adjectives, not nouns.

**Comment by TheBerkin** [comment]
I'll change the examples to reflect that, but connotations could definitely be used for some nouns as well in the actual implementation.
